// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/dijkvy/geocentric/config"
	"github.com/dijkvy/geocentric/log"
	"github.com/dijkvy/geocentric/log/zaplog"
	"go.uber.org/zap"
)

// Injectors from wire.go:

func InitLoggerHelper(logger *zap.Logger, opt ...log.Option) (log.Helper, error) {
	helper := log.NewHelper(logger, opt...)
	return helper, nil
}

func InitZapLogger(cfg *config.ZapConfig) (*zap.Logger, error) {
	logger, err := zaplog.NewZapLogger(cfg)
	if err != nil {
		return nil, err
	}
	return logger, nil
}
